server {
    listen 80 default;
    server_name localhost;
    location / {
        include /etc/nginx/conf.d/includes/proxy.conf;
        include /etc/nginx/conf.d/includes/proxy_ws.conf;
        proxy_pass http://nodered_soa2026:1880/;
    }
    location /adminer {
        include /etc/nginx/conf.d/includes/proxy.conf;
        proxy_pass http://adminer_soa2026:8080/;
    }
}
